### PR TITLE
Adds maliput_full meta package.

### PR DESCRIPTION
**Pull request by francocipollone**
Related to #279

### CODE REVIEW

**Review by agalbachicar — DISMISSED** [review]
LGTM

**Review by tfoote — APPROVED** [review]
lgtm. The repos file may want to be not in the hidden directory and be a reference file for checking things out from source in the future.

**Comment by francocipollone** [comment]
> lgtm. The repos file may want to be not in the hidden directory and be a reference file for checking things out from source in the future.

Thanks, it makes sense. d47fa5d

**Comment by tfoote** [comment]
The repo is ready now: https://github.com/ros2-gbp/maliput_infrastructure-release

**Pull request merged**
